resources:
- ../base
- env-ops-configmap.yaml
- r94dbfc8/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r94dbfc8/revision-patch.yaml
  target:
    kind: Service
- path: r94dbfc8/routing-patch.yaml
  target:
    kind: Service