resources:
- ../base
- env-ops-configmap.yaml
- rc076ee9/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rc076ee9/revision-patch.yaml
  target:
    kind: Service
- path: rc076ee9/routing-patch.yaml
  target:
    kind: Service