resources:
- ../base
- env-ops-configmap.yaml
- r62c7f78/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r62c7f78/revision-patch.yaml
  target:
    kind: Service
- path: r62c7f78/routing-patch.yaml
  target:
    kind: Service